In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv('/Users/garimajain/Desktop/Non-Tech_Diversity.csv')

In [3]:
df

,Company,Year,Female %,Male %,% White,% Asian,% Latino,% Black,% Multi,% Other & Undeclared
0,Facebook,2014,47,53,63.0,24.0,6.0,2.0,4.0,1
1,LinkedIn,2014,47,53,63.0,26.0,5.0,3.0,3.0,<1
2,Pinterest,2014,34,66,NaN,NaN,NaN,NaN,NaN,NaN
3,Tumblr,2014,52,47,63.0,24.0,6.0,3.0,2.0,2
4,Twitter,2014,50,50,60.0,23.0,3.0,4.0,5.0,5
5,Google,2014,48,52,65.0,23.0,4.0,3.0,5.0,<1
6,Apple,2014,35,65,56.0,14.0,9.0,9.0,3.0,9
7,eBay,2014,49,51,70.0,11.0,7.0,9.0,1.0,1
8,Non-Tech Average,2014,45,55,63.0,21.0,6.0,5.0,3.0,4
9,Facebook,2015,48,52,62.0,24.0,7.0,3.0,3.0,1
10,LinkedIn,2015,50,50,66.0,25.0,4.0,3.0,2.0,<1
11,Pinterest,2015,34,66,67.0,22.0,3.0,2.0,5.0,1
12,Tumblr,2015,45,54,66.0,19.0,6.0,3.0,3.0,3
13,Twitter,2015,50,50,62.0,24.0,4.0,4.0,1.0,5
14,Google,2015,47,53,64.0,23.0,4.0,4.0,4.0,<1
15,Apple,2015,37,63,55.0,11.0,14.0,10.0,3.0,7
16,eBay,2015,49,51,69.0,10.0,7.0,11.0,2.0,<1
17,Non-Tech Average,2015,45,55,64.0,20.0,6.0,5.0,3.0,3
18,Facebook,2016,53,47,60.0,25.0,7.0,5.0,3.0,1
19,LinkedIn,2016,52,48,67.0,20.0,6.0,4.0,3.0,1
20,Pinterest,2016,66,34,63.0,23.0,5.0,3.0,4.0,1
21,Tumblr,2016,56,44,67.0,18.0,6.0,3.0,3.0,4
22,Twitter,2016,53,47,62.0,25.0,5.0,5.0,3.0,1
23,Google,2016,47,53,63.0,23.0,5.0,4.0,4.0,<1
24,Apple,2016,38,62,58.0,12.0,16.0,11.0,3.0,1
25,eBay,2016,48,52,71.0,16.0,7.0,4.0,1.0,1
26,Non-Tech Average,2016,52,48,64.0,20.0,7.0,5.0,3.0,1

In [4]:
df.to_csv('Non-Tech.csv', index=False, encoding='utf-8')